### Responds with a list of all todos as a JSON Array
### handled by pages/api/todos/index.js
GET http://localhost:3000/api/toDOH HTTP/1.1

### Insert a new todo using the data from the request.body
### Responds with the insert result as a JSON Object
### handled by pages/api/todos/index.js
POST http://localhost:3000/api/toDOH HTTP/1.1
Content-Type: application/json

{
    "name": "Something that needs to be done",
    "isDone": false
}

### Responds with a singular todo matching the provided id as a JSON Object
### handled by pages/api/todos/[todoId].js
GET http://localhost:3000/api/toDOH/616fdd94132f70eebaf29f53 HTTP/1.1


### Updates a todo matching the provided id using the data from the request.body
### Responds with the update result as a JSON Object
### handled by pages/api/todos/[todoId].js
PUT http://localhost:3000/api/toDOH/616fdd94132f70eebaf29f53 HTTP/1.1
Content-Type: application/json

{
    "name": "Something else that needs to be done!"
}

### Deletes a todo matching the provided id
### Responds with the delete result as a JSON Object
### handled by pages/api/todos/[todoId].js
DELETE http://localhost:3000/api/toDOH/616fdd94132f70eebaf29f54 HTTP/1.1